# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lamp_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12lamp_service.proto\x12\x04lamp\"\x15\n\x13LigarLampadaRequest\"\x18\n\x16\x44\x65sligarLampadaRequest\"\x19\n\x06Status\x12\x0f\n\x07message\x18\x01 \x01(\t2\x85\x01\n\x0bLampService\x12\x37\n\x0cligarLampada\x12\x19.lamp.LigarLampadaRequest\x1a\x0c.lamp.Status\x12=\n\x0f\x64\x65sligarLampada\x12\x1c.lamp.DesligarLampadaRequest\x1a\x0c.lamp.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lamp_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LIGARLAMPADAREQUEST']._serialized_start=28
  _globals['_LIGARLAMPADAREQUEST']._serialized_end=49
  _globals['_DESLIGARLAMPADAREQUEST']._serialized_start=51
  _globals['_DESLIGARLAMPADAREQUEST']._serialized_end=75
  _globals['_STATUS']._serialized_start=77
  _globals['_STATUS']._serialized_end=102
  _globals['_LAMPSERVICE']._serialized_start=105
  _globals['_LAMPSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
