# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lamp_service_pb2 as lamp__service__pb2


class LampServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ligarLampada = channel.unary_unary(
                '/lamp.LampService/ligarLampada',
                request_serializer=lamp__service__pb2.LigarLampadaRequest.SerializeToString,
                response_deserializer=lamp__service__pb2.Status.FromString,
                )
        self.desligarLampada = channel.unary_unary(
                '/lamp.LampService/desligarLampada',
                request_serializer=lamp__service__pb2.DesligarLampadaRequest.SerializeToString,
                response_deserializer=lamp__service__pb2.Status.FromString,
                )


class LampServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ligarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def desligarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LampServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ligarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.ligarLampada,
                    request_deserializer=lamp__service__pb2.LigarLampadaRequest.FromString,
                    response_serializer=lamp__service__pb2.Status.SerializeToString,
            ),
            'desligarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.desligarLampada,
                    request_deserializer=lamp__service__pb2.DesligarLampadaRequest.FromString,
                    response_serializer=lamp__service__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lamp.LampService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LampService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ligarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lamp.LampService/ligarLampada',
            lamp__service__pb2.LigarLampadaRequest.SerializeToString,
            lamp__service__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def desligarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lamp.LampService/desligarLampada',
            lamp__service__pb2.DesligarLampadaRequest.SerializeToString,
            lamp__service__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
