# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import water_pump_service_pb2 as water__pump__service__pb2


class WaterPumpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TurnOnWaterPump = channel.unary_unary(
                '/water_pump_service.WaterPumpService/TurnOnWaterPump',
                request_serializer=water__pump__service__pb2.TurnOnWaterPumpRequest.SerializeToString,
                response_deserializer=water__pump__service__pb2.Status.FromString,
                )
        self.TurnOffWaterPump = channel.unary_unary(
                '/water_pump_service.WaterPumpService/TurnOffWaterPump',
                request_serializer=water__pump__service__pb2.TurnOffWaterPumpRequest.SerializeToString,
                response_deserializer=water__pump__service__pb2.Status.FromString,
                )


class WaterPumpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TurnOnWaterPump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TurnOffWaterPump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterPumpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TurnOnWaterPump': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOnWaterPump,
                    request_deserializer=water__pump__service__pb2.TurnOnWaterPumpRequest.FromString,
                    response_serializer=water__pump__service__pb2.Status.SerializeToString,
            ),
            'TurnOffWaterPump': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOffWaterPump,
                    request_deserializer=water__pump__service__pb2.TurnOffWaterPumpRequest.FromString,
                    response_serializer=water__pump__service__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'water_pump_service.WaterPumpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WaterPumpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TurnOnWaterPump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/water_pump_service.WaterPumpService/TurnOnWaterPump',
            water__pump__service__pb2.TurnOnWaterPumpRequest.SerializeToString,
            water__pump__service__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TurnOffWaterPump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/water_pump_service.WaterPumpService/TurnOffWaterPump',
            water__pump__service__pb2.TurnOffWaterPumpRequest.SerializeToString,
            water__pump__service__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
